name: Trigger Automic Automation

on: [push]

jobs:
  trigger-automic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Increase fetch depth to include previous commits

      - name: Print environment variables
        run: env

      - name: Print working directory
        run: pwd

      - name: List files in the repo
        run: ls -R

      - name: Print contents of .git directory
        run: ls -R .git

      - name: Print git status
        run: git status

      - name: Print git log
        run: git log -n 5

      - name: Print diff links
        run: |
          echo "Previous SHA: ${{ github.event.before }}"
          echo "Current SHA: ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changes.txt
          cat changes.txt
          while IFS= read -r file; do
            diff_link="https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}#diff-$(echo ${file} | sed 's#/#%2F#g')"
            echo "File: ${file}"
            echo "Diff link: ${diff_link}"
          done < changes.txt
