name: Trigger Automic Automation

on: [push]

jobs:
  trigger-automic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Print environment variables
        run: env

      - name: Print working directory
        run: pwd

      - name: List files in the repo
        run: ls -R

      - name: Print contents of .git directory
        run: ls -R .git

      - name: Print git status
        run: git status

      - name: Print git log
        run: git log -n 5

      - name: Determine comparison commit
        id: determine-commit
        run: |
          # Find the last commit with "Production" in its message
          production_commit=$(git log --grep="Production" -1 --pretty=format:"%H")
          
          # Fallback to the previous commit if no "Production" commit is found
          if [ -z "$production_commit" ]; then
            production_commit=${{ github.event.before }}
          fi
          
          echo "Comparison Commit SHA: $production_commit"
          echo "::set-output name=comparison_commit::$production_commit"

      - name: Print diff links
        run: |
          echo "Comparison SHA: ${{ steps.determine-commit.outputs.comparison_commit }}"
          echo "Current SHA: ${{ github.sha }}"
          git diff --name-only ${{ steps.determine-commit.outputs.comparison_commit }} ${{ github.sha }} > changes.txt
          cat changes.txt
          while IFS= read -r file; do
            diff_link="https://github.com/${{ github.repository }}/compare/${{ steps.determine-commit.outputs.comparison_commit }}...${{ github.sha }}?diff=split&w=&short_path=$(echo ${file} | sed 's#/#%2F#g')"
            echo "File: ${file}"
            echo "Diff link: ${diff_link}"
          done < changes.txt

      - name: Send webhook to Automic Automation
        run: |
          while IFS= read -r file; do
            if [ "$file" != ".github/workflows/trigger-automic.yml" ]; then
              diff_link="https://github.com/${{ github.repository }}/compare/${{ steps.determine-commit.outputs.comparison_commit }}...${{ github.sha }}?diff=split&w=&short_path=$(echo ${file} | sed 's#/#%2F#g')"
              curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
                --header 'Content-Type: application/json' \
                --user '103/UDM/UDM:udm' \
                --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${file}\", \"&DIFF_LINK#\": \"${diff_link}\"}}"
            else
              echo "Skipping curl command for .github/workflows/trigger-automic.yml"
            fi
          done < changes.txt
