name: Create Diff and Notify Automic

on:
  push:
    branches:
      - main  # Adjust if you want this to run on different branches

jobs:
  create-diff-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest commit SHA and committed file
        id: get_commit_info
        run: |
          LATEST_COMMIT_SHA=$(git rev-parse HEAD)
          COMMITTED_FILE=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT_SHA)
          echo "LATEST_COMMIT_SHA=${LATEST_COMMIT_SHA}" >> $GITHUB_ENV
          echo "COMMITTED_FILE=${COMMITTED_FILE}" >> $GITHUB_ENV

      - name: Find most recent "PRODUCTION" commit or fallback to previous commit
        id: get_baseline_commit
        run: |
          PRODUCTION_COMMIT=$(git log --grep="PRODUCTION" -n 1 --pretty=format:%H)
          if [ -z "$PRODUCTION_COMMIT" ]; then
            BASELINE_COMMIT=$(git rev-parse HEAD^)
          else
            BASELINE_COMMIT=$PRODUCTION_COMMIT
          fi
          echo "BASELINE_COMMIT=${BASELINE_COMMIT}" >> $GITHUB_ENV

      - name: Generate diff for the committed file
        id: generate_diff
        run: |
          DIFF=$(git diff $BASELINE_COMMIT $LATEST_COMMIT_SHA -- ${{ env.COMMITTED_FILE }})
          echo "DIFF=${DIFF}" >> $GITHUB_ENV
          echo "${DIFF}" > diff.txt

      - name: Create diff link (e.g., using a gist or another service)
        id: create_diff_link
        run: |
          # This is a placeholder command. Replace it with actual logic to upload the diff and get a link.
          DIFF_LINK="https://example.com/diff/${{ github.sha }}"  # Replace with actual diff hosting logic
          echo "DIFF_LINK=${DIFF_LINK}" >> $GITHUB_ENV

      - name: Notify Automic Automation
        run: |
          curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
          --header 'Content-Type: application/json' \
          --user '103/UDM/UDM:udm' \
          --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${{ env.COMMITTED_FILE }}\", \"&DIFF_LINK#\": \"${{ env.DIFF_LINK }}\", \"&LATEST_COMMIT_SHA#\": \"${{ env.LATEST_COMMIT_SHA }}\"}}"
