name: Create Diff and Notify Automic

on:
  push:
    branches:
      - main  # Adjust if you want this to run on different branches

jobs:
  create-diff-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest commit message and file
        id: get_commit_info
        run: |
          LATEST_COMMIT_SHA=$(git rev-parse HEAD)
          COMMITTED_FILE=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT_SHA)
          echo "LATEST_COMMIT_SHA=${LATEST_COMMIT_SHA}" >> $GITHUB_ENV
          echo "COMMITTED_FILE=${COMMITTED_FILE}" >> $GITHUB_ENV

      - name: Get baseline commit
        id: get_baseline_commit
        run: |
          BASELINE_COMMIT=$(git log --grep="PRODUCTION" -n 1 --pretty=format:%H || git rev-parse HEAD^)
          echo "BASELINE_COMMIT=${BASELINE_COMMIT}" >> $GITHUB_ENV

      - name: Generate diff
        id: generate_diff
        run: |
          DIFF=$(git diff $BASELINE_COMMIT $LATEST_COMMIT_SHA -- ${{ env.COMMITTED_FILE }})
          echo "DIFF=${DIFF}" >> $GITHUB_ENV

      - name: Create diff link (e.g., using a gist or another service)
        id: create_diff_link
        run: |
          DIFF_LINK="https://example.com/diff/${{ github.sha }}" # Replace this with actual logic to host the diff
          echo "DIFF_LINK=${DIFF_LINK}" >> $GITHUB_ENV

      - name: Notify Automic Automation
        run: |
          curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
          --header 'Content-Type: application/json' \
          --user '103/UDM/UDM:udm' \
          --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${{ env.COMMITTED_FILE }}\", \"&DIFF_LINK#\": \"${{ env.DIFF_LINK }}\", \"&LATEST_COMMIT_SHA#\": \"${{ env.LATEST_COMMIT_SHA }}\"}}"
