name: Trigger Automic Automation

on:
  push:
    branches:
      - main

jobs:
  trigger-automic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get the SHA of the previous commit
      id: previous_commit
      run: |
        previous_commit=$(git log -2 --format=format:%H | tail -n 1)
        echo "Previous Commit SHA: $previous_commit"
        echo "previous_commit=$previous_commit" >> $GITHUB_ENV

    - name: Find the last commit with "Production" in the commit message
      id: production_commit
      run: |
        production_commit=""
        echo "Searching for commits with 'Production' in the commit messages..."
        for sha in $(git rev-list HEAD); do
          commit_message=$(git log -1 --format=%B $sha)
          echo "Checking commit $sha"
          if [[ $commit_message == *"Production"* ]]; then
            echo "Found 'Production' in commit message for commit $sha"
            production_commit=$sha
            break
          fi
        done

        if [ -z "$production_commit" ]; then
          echo "No commit with 'Production' found in commit messages. Using previous commit."
          production_commit=${{ env.previous_commit }}
        fi

        echo "Comparison Commit SHA: $production_commit"
        echo "comparison_commit=$production_commit" >> $GITHUB_ENV

    - name: Generate diff link and trigger Automic
      run: |
        previous_commit=${{ env.comparison_commit }}
        current_commit=$(git rev-parse HEAD)

        echo "Comparison SHA: $previous_commit"
        echo "Current SHA: $current_commit"

        git diff --name-only $previous_commit $current_commit > changes.txt
        cat changes.txt

        while IFS= read -r file; do
          if [ "$file" != ".github/workflows/trigger-automic.yml" ]; then
            # Construct the comparison URL
            encoded_file=$(echo ${file} | sed 's#/#%2F#g')
            diff_link="https://github.com/Project-Hail-Mary/OPLAN/compare/${previous_commit}...${current_commit}?diff=split%26w=%26short_path=${encoded_file}"

            echo "Constructed diff link: ${diff_link}"  # Debug output for the URL

            curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
              --header 'Content-Type: application/json' \
              --user '103/UDM/UDM:udm' \
              --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${file}\", \"&DIFF_LINK#\": \"${diff_link}\"}}"
          else
            echo "Skipping curl command for .github/workflows/trigger-automic.yml"
          fi
        done < changes.txt
