name: Find Production Commit and Generate Diff

on: [push]

jobs:
  find-production-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Find Production Commit
      id: find_commit
      run: |
        production_commit=$(git log --grep="PRODUCTION" -n 1 --format="%H" || echo "none")
        latest_commit=$(git rev-parse HEAD)
        previous_commit=$(git rev-parse HEAD~1)
        echo "Latest Commit SHA: $latest_commit"
        echo "Previous Commit SHA: $previous_commit"
        echo "Production Commit SHA: $production_commit"
        echo "::set-output name=production_commit::$production_commit"
        echo "::set-output name=latest_commit::$latest_commit"
        echo "::set-output name=previous_commit::$previous_commit"

    - name: Get Committed File
      id: get_file
      run: |
        committed_file=$(git diff --name-only HEAD~1 HEAD)
        echo "Committed file: $committed_file"
        echo "::set-output name=committed_file::$committed_file"

    - name: Generate Diff for Committed File
      run: |
        production_commit=${{ steps.find_commit.outputs.production_commit }}
        latest_commit=${{ steps.find_commit.outputs.latest_commit }}
        previous_commit=${{ steps.find_commit.outputs.previous_commit }}
        committed_file=${{ steps.get_file.outputs.committed_file }}
        
        if [ "$production_commit" != "none" ]; then
          echo "Using Production Commit as baseline."
          git diff $production_commit $latest_commit -- $committed_file > changes.txt
        else
          echo "Using Previous Commit as baseline."
          git diff $previous_commit $latest_commit -- $committed_file > changes.txt
        fi

    - name: Call Automic
      run: |
        latest_commit=${{ steps.find_commit.outputs.latest_commit }}
        committed_file=${{ steps.get_file.outputs.committed_file }}
        diff_link="https://github.com/Project-Hail-Mary/OPLAN/commit/${latest_commit}"
        file_commit_link="https://github.com/Project-Hail-Mary/OPLAN/commit/${latest_commit}"
        
        payload=$(jq -n \
          --arg latest_commit "$latest_commit" \
          --arg previous_commit "${{ steps.find_commit.outputs.previous_commit }}" \
          --arg production_commit "${{ steps.find_commit.outputs.production_commit }}" \
          --arg changes "$(cat changes.txt)" \
          '{latest_commit: $latest_commit, previous_commit: $previous_commit, production_commit: $production_commit, changes: $changes}')

        curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
          --header 'Content-Type: application/json' \
          --user '103/UDM/UDM:udm' \
          --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${file_commit_link}\", \"&DIFF_LINK#\": \"${diff_link}\", \"&LATEST_COMMIT_SHA#\": \"${latest_commit}\"}}"
