name: Trigger Automic

on:
  push:
    branches:
      - main

jobs:
  find-production-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Find production commit
        id: find_commit
        run: |
          production_commit=$(git log --grep=PRODUCTION -1 --format=format:%H || echo "none")
          latest_commit=$(git rev-parse HEAD)
          previous_commit=$(git rev-parse HEAD^)
          echo "Latest Commit SHA: $latest_commit"
          echo "Production Commit SHA: $production_commit"
          echo "Previous Commit SHA: $previous_commit"
          echo "::set-output name=latest_commit::$latest_commit"
          echo "::set-output name=production_commit::$production_commit"
          echo "::set-output name=previous_commit::$previous_commit"

      - name: Determine comparison commit
        id: determine_commit
        run: |
          if [ "${{ steps.find_commit.outputs.production_commit }}" != "none" ]; then
            comparison_commit=${{ steps.find_commit.outputs.production_commit }}
          else
            if [ "${{ steps.find_commit.outputs.latest_commit }}" != "${{ steps.find_commit.outputs.previous_commit }}" ]; then
              comparison_commit=${{ steps.find_commit.outputs.previous_commit }}
            else
              comparison_commit=${{ steps.find_commit.outputs.latest_commit }}
            fi
          fi
          echo "Comparison Commit SHA: $comparison_commit"
          echo "::set-output name=comparison_commit::$comparison_commit"

      - name: Generate changes list
        id: generate_changes
        run: |
          comparison_commit=${{ steps.determine_commit.outputs.comparison_commit }}
          latest_commit=${{ steps.find_commit.outputs.latest_commit }}
          echo "Comparing $comparison_commit with $latest_commit"
          git diff --name-only $comparison_commit $latest_commit > changes.txt
          cat changes.txt

      - name: Trigger Automic
        run: |
          file=$(cat changes.txt | head -n 1)
          if [ "$file" != ".github/workflows/trigger-automic.yml" ]; then
            encoded_file=$(echo ${file} | sed 's#/#%2F#g')
            diff_link="https://github.com/Project-Hail-Mary/OPLAN/compare/${{ steps.determine_commit.outputs.comparison_commit }}...${{ steps.find_commit.outputs.latest_commit }}?diff=split%26w=%26short_path=${encoded_file}"
            file_commit_link="${{ steps.find_commit.outputs.latest_commit }}"
            echo "Constructed diff link: ${diff_link}"

            curl --location 'http://104.196.70.116:8088/ae/api/v1/103/executions' \
              --header 'Content-Type: application/json' \
              --user '103/UDM/UDM:udm' \
              --data "{\"object_name\": \"GITHUB.PRE.APPROVE\", \"inputs\": {\"&FILE#\": \"${file_commit_link}\", \"&DIFF_LINK#\": \"${diff_link}\", \"&LATEST_COMMIT_SHA#\": \"${{ steps.find_commit.outputs.latest_commit }}\"}}"
          else
            echo "Skipping curl command for .github/workflows/trigger-automic.yml"
          fi
